version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

    # Restore bundle cache
      - restore_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}

      - run: |
          sudo mv /usr/local/lib/ruby/gems/2.4.0/specifications/{default/,}bundler-1.16.0.gemspec
          sudo gem uninstall bundler -a -x
          sudo gem install bundler --version 1.16
          sudo gem install middleman-cli

      # Bundle install dependencies
      - run: bundle install

      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: deploy to s3
          command: |
            node index.js
            middleman build --clean --verbose
            middleman s3_sync
