version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout

    # Restore bundle cache
      - restore_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: deploy to s3
          command: |
            node index.js
            bundle exec middleman build --clean --verbose
            bundle exec middleman s3_sync

